### ISSUE TITLE
Unhandled exception occured while templating in task

### ISSUE THREAD

**Issue by albuch** [DataDog/ansible-datadog#401] opened 2021-11-03 15:49 UTC
Datadog installation role somehow fails for one of its tasks. This used to work, and there are no code config changes related to the datadog agent installation or configuration in our ansible scripts. 

# Error message
```
TASK [Datadog.datadog : Defend against defined but null datadog_checks variable] *************************************************************************************************************************
task path: /Users/xxxxxxx/.ansible/roles/Datadog.datadog/tasks/sanitize-checks.yml:1
fatal: [twistlock]: FAILED! => {
    "msg": "An unhandled exception occurred while templating '{'disk': {'init_config': None, 'instances': [{'name': 'xxxxxxxxxx', 'use_mount': False, 'mount_point_blacklist': ['/var/lib/docker/containers/.*', '/var/lib/docker/overlay2/.*']}]}, 'prometheus': {'init_config': None, 'instances': [{'name': 'xxxxxxxx', 'prometheus_url': 'https://prometheus-user:{{ twistlock_prometheus_user_password | urlencode() }}@txxxxxxxxxxx/api/v1/metrics', 'namespace': 'prometheus', 'metrics': ['twistlock_*', 'go*', 'process*'], 'max_returned_metrics': 100}]}, 'docker': {'init_config': None, 'instances': [{'name': 'xxxxxxxxxxx'}]}}'. Error was a <class 'ValueError'>, original message: not enough values to unpack (expected 2, got 1)"
}
```
Enabling verbose logging `-vvv` didn't show any more info.

# Datadog Agent Config
```
datadog_api_key: "{{datadog_api_key_vaulted}}"
datadog_site: "datadoghq.eu"
datadog_config:
  hostname: "xxxxxxx
  tags: "Owner:xxxxxx"
  log_level: INFO
  apm_config:
    enabled: false
  logs_enabled: false
  process_config:
    enabled: "true"
    scrub_args: true
    custom_sensitive_words: ['*password*','dd_api_key']
datadog_additional_groups: docker
datadog_checks:
  disk:
    init_config:
    instances:
      - name: 'xxxxxxxxx'
        use_mount: false
        mount_point_blacklist:
          - /var/lib/docker/containers/.*
          - /var/lib/docker/overlay2/.*
  prometheus:
    init_config:
    instances:
      - name: 'xxxxxxxxx'
        prometheus_url: "https://prometheus-user:{{ twistlock_prometheus_user_password | urlencode() }}@xxxxxxxxx/api/v1/metrics"
        namespace: 'prometheus'
        metrics:
          - 'twistlock_*'
          - 'go*'
          - 'process*'
        max_returned_metrics: 100
  docker:
    init_config:
    instances:
      - name: 'xxxxxxx'
```

I can't figure out from the error message what the issue is. We use the following versions of ansible and ansible-datadog.
```
% ansible --version
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/xxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxxxxx/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/xxxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxxxxxxx/Library/Python/3.9/bin/ansible
  python version = 3.9.7 (default, Oct 12 2021, 22:38:23) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
% ansible-galaxy list
# /Users/xxxxxx/.ansible/roles
- datadog.datadog, 4.12.0
[WARNING]: - the configured path /usr/share/ansible/roles does not exist.
[WARNING]: - the configured path /etc/ansible/roles does not exist.
```

**Comment by bkabrda** [comment] 2021-11-04 07:17
Hi 👋 thanks for the report! I released 4.12.0 yesterday which adds this task, so it's almost certain that this new task is the cause. However, I can't reproduce the problem with your exact config. Could you send me the output of `pip list` so I could reproduce your exact environment? In the meanwhile, pinning the role to 4.11.0 should help you until we figure out what's wrong and release a bugfix version. Thanks!

**Comment by bkabrda** [comment] 2021-11-04 07:32
Additionally, could you please describe where the `twistlock_prometheus_user_password` variable comes from? Since the error raised is `An unhandled exception occurred while templating` and this is the only template variable in the config, it might be important when debugging. Thanks!

**Comment by albuch** [comment] 2021-11-04 15:38
The issue appears with previous versions (e.g. v4.4.0) as well with a different task (`Ensure configuration directories are present for each Datadog check`) later in the chain. So probably more related to an environment issue as it used to work with v4.4.0 beforehand and the only thing that might have changed are dependencies or ansible version due to system updates.
The `twistlock_prometheus_user_password` is an ansible vaulted string.

```
pip list
Package      Version
------------ -------
ansible      4.7.0
ansible-core 2.11.6
cffi         1.15.0
cryptography 35.0.0
Jinja2       3.0.2
MarkupSafe   2.0.1
packaging    21.2
pip          21.3.1
pycparser    2.20
pyparsing    2.4.7
PyYAML       6.0
resolvelib   0.5.4
setuptools   57.4.0
six          1.16.0
wheel        0.37.0
```

**Comment by bkabrda** [comment] 2021-11-05 06:28
Ok, thanks for all the additional info. I'll try to look into this closer to see what's wrong.

**Comment by bkabrda** [comment] 2021-11-05 07:27
Ok, so I can reproduce this, it seems that the problem is only if you apply `urlencode` on a vaulted variable and it's actually an Ansible problem: https://github.com/ansible/ansible/issues/73054

Could you try creating another vaulted variable, which would be already url-encoded and using that instead of applying the `urlencode` filter? That seems to be the best workaround for me (I'm afraid that if this is confirmed I can't help you much, as this is an ansible core issue).

**Comment by albuch** [comment] 2021-11-05 09:34
Thanks @bkabrda for finding the route cause! Will apply the workaround.

**Comment by bkabrda** [comment] 2021-11-05 10:52
@albuch awesome. I'm going to go ahead and close this issue. Feel free to let me know if you need anything else!

**Closed as completed by bkabrda** 2021-11-05 10:52 UTC
