### ISSUE TITLE
/etc/datadog-agent/conf.d does not exist

### ISSUE THREAD

**Issue by excalq** [DataDog/ansible-datadog#111] opened 2018-03-16 22:08 UTC
I'm noticing that when doing a fresh install of the DataDog agent (v6 via the ansible-datadog v2.0.1 role), that we get an error due to a non-existent directory. It's easy to fix manually with a `mkdir -p`, but I wanted to surface the issue.

```
TASK [monitoring/Datadog.datadog : Create a configuration file for each Datadog check] 
*******************************
failed: [our.ansiblized.host] (item=postfix) => {
    "changed": false,
    "checksum": "fc33569545c6669cbea509271db144ec81ddc13f",
    "item": "postfix"
}
MSG:
Destination directory /etc/datadog-agent/conf.d does not exist
```

**Comment by surrealchemist** [comment] 2018-03-27 13:59
Seeing the same here ever since I upgraded the playbooks to the latest galaxy ones.
Maybe this task in agent6.yml should include the full path with conf.d if it expects it to be there: 

```
- name: Create /etc/datadog-agent
  file:
    dest: /etc/datadog-agent
    state: directory
```

**Comment by hush-hush** [comment] 2018-04-24 16:07
Hi @excalq and @surrealchemist,

Thanks for reporting the issue, but I'm having difficulties reproducing it (using version 2.0.1).
The datadog-agent package (deb and rpm) should provide that folder (`/etc/datadog-agent/conf.d`) and the agent6 task create `/etc/datadog-agent` since version `1.5.0` (https://github.com/DataDog/ansible-datadog/commit/380b44c1dfbdb1c2905b8e3fa8fc5ea73afefbc4#diff-66cdabd1217b27b0049f218f9613dcf3R2).

What version of which OS are you using ?
Could you share your playbook (after removing every sensitive information of course) ?

Thanks

**Comment by surrealchemist** [comment] 2018-04-24 17:10
My playbook is pretty simple. It just runs the role and adds a single check, with datadog_api_key set in my group_vars 
Never had this come up before with previous version, so maybe the new packages aren't creating the appropriate directories. If I am not mistaken the previous packages also placed some default configuration files as well, which I no longer see. 

```
- name:              Configure wordpress sites
  hosts:             tag_application_wordpress
  become:            yes
  roles:
    - wordpress
    - { role: Datadog.datadog, become: yes }
  vars:
    datadog_config:
      tags:          "wordpress"
    datadog_checks:
      apache:
        init_config:
        instances:
          - apache_status_url: "http://localhost/server-status?auto"
```

/etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

dpkg -l datadog-agent 
```
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-============================================================
ii  datadog-agent               1:5.22.3-1         amd64              Datadog Monitoring Agent
```

**Comment by hush-hush** [comment] 2018-04-24 17:47
Thanks for the information @surrealchemist !

Are you sure to use the version `2.0.1` from the datadog role, starting from version `2.0.0` the role install agent6 by default unless `datadog_agent5` is set to true. I can see you have version 5.22.3 installed.

Could you run `ansible-galaxy list  Datadog.datadog` ?

**Comment by surrealchemist** [comment] 2018-04-27 15:33
It lists as 2.0.1. I was using the previous version for a while till one day I started getting ssl security warnings from python (I think because of a change over at github). Somewhere along the way while fixing everything I ended up just putting the latest version of the playbook which happened to be this one.
At some point I had errors relating to the gpg key for datadog, so I don't know where the package came from now.

```
$ ansible-galaxy list -p roles/ Datadog.datadog
- Datadog.datadog, 2.0.1
```

```
$ apt-cache policy datadog-agent
datadog-agent:
  Installed: 1:5.22.3-1
  Candidate: 1:5.22.3-1
  Version table:
 *** 1:5.22.3-1 100
        100 /var/lib/dpkg/status
```

**Comment by hush-hush** [comment] 2018-05-14 19:43
Sorry for the late answer @surrealchemist !

The debian repo installed by the role should be `deb https://apt.datadoghq.com/ stable 6` (see https://github.com/DataDog/ansible-datadog/blob/2.0.1/defaults/main.yml#L15).

Could you cat `/etc/apt/sources.list.d/datadog.list` and tell me what's in it ? Also is the old debian repo (`deb https://apt.datadoghq.com stable main`) configured anywhere else on the host ?

Could you also try to update apt: `apt-get update` to see if the latest version of `datadog-agent` show in `apt-cache policy datadog-agent` after ? APT should be updated by the role automatically.

**Comment by hush-hush** [comment] 2018-06-21 21:34
Closing this issue, feel free to reopen if needed !

**Closed as completed by hush-hush** 2018-06-21 21:34 UTC
