### ISSUE TITLE
Oracle integration configuration

### ISSUE THREAD

**Issue by edvinas31** [DataDog/ansible-datadog#433] opened 2022-04-15 10:54 UTC
Ansible datadog version I am using: https://github.com/DataDog/ansible-datadog/releases/tag/4.11.0

Hi, when trying to add custom query like shown here https://docs.datadoghq.com/integrations/oracle/?tab=linux#example I get the ../oracle.d/conf.yaml file corrupted. When adding to the ansible code the following:

```
- name: Install Datadog
    import_role:
      name: datadog.datadog
    vars:
      datadog_api_key: "{{ credentials_vault['datadoghq.eu']['api_key_' + oci_tag_env_type] }}"
      datadog_site: "datadoghq.eu"
      datadog_agent_major_version: "6"
      datadog_additional_groups:
        - docker
      datadog_checks:
        oracle:
          init_config:
          
          instances:
            - server: localhost:1521
              service_name: tia
              username: datadog
              password: "{{ cust_vault[cust_name][env_name]['tia_db_datadog_password'] }}"
              jdbc_driver_path: "{{ oracle_home.stdout }}/jdbc/lib/ojdbc8.jar"
              only_custom_queries: true
              # min_collection_interval: 15
              protocol: TCP

              custom_queries:
                - metric_prefix: oracle
                  # Check for tablespace usage for 30 mins and group them by tablespace
                  query:
                     select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
                  columns:
                    - name: tablespace_usage_count
                      type: gauge
                    - name: used_percent
                      type: tag
                    - name: TABLESPACE_SIZE
                      type: tag
                    - name: TABLESPACE_NAME
                      type: tag
      datadog_config:
        process_config:
          enabled: "true"
        hostname_fqdn: true
        tags:
          - client:{{ cust_name }}
          - env:{{ oci_tag_env_type }}
          - os:linux:{{ ansible_facts.distribution }}
    when:
      - cust_name is defined
      - oci_tag_env_type is defined
      - env_name is defined
    tags: datadog
```

In configuration block I get file wrongly configured:

```
[root@paasdev-db01 esu]# cat /etc/datadog-agent/conf.d/oracle.d/conf.yaml
init_config: null
instances:
-   custom_queries:
    -   columns:
        -   name: tablespace_usage_count
            type: gauge
        -   name: used_percent
            type: tag
        -   name: TABLESPACE_SIZE
            type: tag
        -   name: TABLESPACE_NAME
            type: tag
        metric_prefix: oracle
        query: |-
            select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
    jdbc_driver_path: /u01/app/oracle/product/19.0.0/dbhome_1/jdbc/lib/ojdbc8.jar
    only_custom_queries: true
    password: PAAS_DEV#datadog
    protocol: TCP
    server: localhost:1521
    service_name: tia
    username: datadog
```

Could you tell me why the template is switched places?

What I expect to see is:

```
[root@paasdev-db01 esu]# cat /etc/datadog-agent/conf.d/oracle.d/conf.yaml
init_config: null
instances:
-  server: localhost:1521
    jdbc_driver_path: /u01/app/oracle/product/19.0.0/dbhome_1/jdbc/lib/ojdbc8.jar
    only_custom_queries: true
    password: PAAS_DEV#datadog
    protocol: TCP
    service_name: tia
    username: datadog
    custom_queries:
      - metric_prefix: oracle
        # Check for tablespace usage for 30 mins and group them by tablespace
        query:
           select to_binary_float(used_percent),to_binary_float(TABLESPACE_SIZE), to_binary_float(USED_SPACE), TABLESPACE_NAME from sys.dba_tablespace_usage_metrics where used_percent > 20
        columns:
          - name: tablespace_usage_count
            type: gauge
          - name: used_percent
            type: tag
          - name: TABLESPACE_SIZE
            type: tag
          - name: TABLESPACE_NAME
            type: tag
```

**Comment by bkabrda** [comment] 2022-04-19 11:36
Hey 👋 thanks for submitting the issue. Can you be more elaborate on what the problem is?

If you're referring to the fact that the keys in the `instances[0]` dict switched places, that's ok, because ordering of the keys doesn't matter (Ansible doesn't preserve it, and I think it orders the keys alphabetically IIRC when rendering the config file). Agent also doesn't care about the ordering of the keys, so the example you posted above should work fine - if not, please let me know what error you get in the agent logs when the Agent tries to parse the config. Thanks!

**Comment by nainysharma** [comment] 2022-04-20 08:34
I do not see any error reported in the agent log .


2022-04-20 10:22:59 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:uptime | Running check...
2022-04-20 10:22:59 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:56 in CheckFinished) | check:uptime | Done running check, next runs will be logged every 500 runs
2022-04-20 10:23:00 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:memory | Running check...
2022-04-20 10:23:00 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:56 in CheckFinished) | check:memory | Done running check, next runs will be logged every 500 runs
2022-04-20 10:23:01 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:io | Running check...
2022-04-20 10:23:01 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:56 in CheckFinished) | check:io | Done running check, next runs will be logged every 500 runs
2022-04-20 10:23:02 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:disk | Running check...
2022-04-20 10:23:02 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:56 in CheckFinished) | check:disk | Done running check, next runs will be logged every 500 runs
2022-04-20 10:23:03 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:oracle | Running check...
2022-04-20 10:23:07 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:network | Running check...
2022-04-20 10:23:08 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:load | Running check...
2022-04-20 10:23:09 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:file_handle | Running check...
2022-04-20 10:23:10 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:cpu | Running check...
2022-04-20 10:23:14 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:uptime | Running check...
2022-04-20 10:23:15 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:memory | Running check...
2022-04-20 10:23:16 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:io | Running check...
2022-04-20 10:23:17 CEST | CORE | INFO | (pkg/collector/worker/check_logger.go:37 in CheckStarted) | check:disk | Running check...
2022-04-20 10:26:46 CEST | CORE | INFO | (pkg/serializer/serializer.go:426 in sendMetadata) | Sent metadata payload, size (raw/compressed): 1906/516 bytes.
2022-04-20 10:26:47 CEST | CORE | INFO | (pkg/serializer/serializer.go:450 in SendProcessesMetadata) | Sent processes metadata payload, size: 1492 bytes.
Connection reset by 141.147.17.98 port 22

**Comment by nainysharma** [comment] 2022-04-20 08:35
Datadog status also looks good .

But i dont see metrics updated for customized query  and oracle integration not working as expected .

**Comment by edvinas31** [comment] 2022-04-20 08:36
![image](https://user-images.githubusercontent.com/49708029/164187050-02b14293-df57-4f61-b4f7-0be352fb5dc7.png)

**Comment by nainysharma** [comment] 2022-04-20 08:37
Please find the datadog-agent status :

  oracle (3.7.0)
    --------------
      Instance ID: oracle:9281fd5a8cbf4e5d [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/oracle.d/conf.yaml
      Total Runs: 60
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 2, Total: 120
      Average Execution Time : 4ms
      Last Execution Date : 2022-04-20 10:36:33 CEST / 2022-04-20 08:36:33 UTC (1650443793000)
      Last Successful Execution Date : 2022-04-20 10:36:33 CEST / 2022-04-20 08:36:33 UTC (1650443793000)


    uptime
    ------
      Instance ID: uptime [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/uptime.d/conf.yaml.default
      Total Runs: 59
      Metric Samples: Last Run: 1, Total: 59
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2022-04-20 10:36:29 CEST / 2022-04-20 08:36:29 UTC (1650443789000)
      Last Successful Execution Date : 2022-04-20 10:36:29 CEST / 2022-04-20 08:36:29 UTC (1650443789000)

**Comment by bkabrda** [comment] 2022-04-20 08:57
So as far as I can see, the configuration file is created successfully and the `oracle` check actually runs, but you don't see the expected data from it. As I'm not an expert on the `oracle` check, could you please go to https://help.datadoghq.com and open a support ticket. Thanks!

I'm going to close this issue now, as I think it's not an Ansible problem, but a problem of the `oracle` integration and/or its configuration.

**Closed as completed by bkabrda** 2022-04-20 08:57 UTC
